name = "cardsafehq-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "card-vault-db"
database_id = "ed48e805-d198-4f01-9d09-f45649ad4f9f"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "varimg"

[vars]
CORS_ORIGIN = "https://cardsafehq.com"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
