-- Sets seed
INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('base1', 'Base', 102, datetime('now')),
  ('base2', 'Jungle', 64, datetime('now')),
  ('basep', 'Wizards Black Star Promos', 53, datetime('now')),
  ('base3', 'Fossil', 62, datetime('now')),
  ('base4', 'Base Set 2', 130, datetime('now')),
  ('base5', 'Team Rocket', 83, datetime('now')),
  ('gym1', 'Gym Heroes', 132, datetime('now')),
  ('gym2', 'Gym Challenge', 132, datetime('now')),
  ('neo1', 'Neo Genesis', 111, datetime('now')),
  ('neo2', 'Neo Discovery', 75, datetime('now')),
  ('si1', 'Southern Islands', 18, datetime('now')),
  ('neo3', 'Neo Revelation', 66, datetime('now')),
  ('neo4', 'Neo Destiny', 113, datetime('now')),
  ('base6', 'Legendary Collection', 110, datetime('now')),
  ('ecard1', 'Expedition Base Set', 165, datetime('now')),
  ('bp', 'Best of Game', 9, datetime('now')),
  ('ecard2', 'Aquapolis', 182, datetime('now')),
  ('ecard3', 'Skyridge', 182, datetime('now')),
  ('ex1', 'Ruby & Sapphire', 109, datetime('now')),
  ('ex2', 'Sandstorm', 100, datetime('now')),
  ('np', 'Nintendo Black Star Promos', 40, datetime('now')),
  ('ex3', 'Dragon', 100, datetime('now')),
  ('ex4', 'Team Magma vs Team Aqua', 97, datetime('now')),
  ('ex5', 'Hidden Legends', 102, datetime('now')),
  ('tk1b', 'EX Trainer Kit Latios', 10, datetime('now'));

INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('tk1a', 'EX Trainer Kit Latias', 10, datetime('now')),
  ('ex6', 'FireRed & LeafGreen', 116, datetime('now')),
  ('pop1', 'POP Series 1', 17, datetime('now')),
  ('ex7', 'Team Rocket Returns', 111, datetime('now')),
  ('ex8', 'Deoxys', 108, datetime('now')),
  ('ex9', 'Emerald', 107, datetime('now')),
  ('ex10', 'Unseen Forces', 145, datetime('now')),
  ('pop2', 'POP Series 2', 17, datetime('now')),
  ('ex11', 'Delta Species', 114, datetime('now')),
  ('ex12', 'Legend Maker', 93, datetime('now')),
  ('tk2b', 'EX Trainer Kit 2 Minun', 12, datetime('now')),
  ('tk2a', 'EX Trainer Kit 2 Plusle', 12, datetime('now')),
  ('pop3', 'POP Series 3', 17, datetime('now')),
  ('ex13', 'Holon Phantoms', 111, datetime('now')),
  ('ex14', 'Crystal Guardians', 100, datetime('now')),
  ('pop4', 'POP Series 4', 17, datetime('now')),
  ('ex15', 'Dragon Frontiers', 101, datetime('now')),
  ('ex16', 'Power Keepers', 108, datetime('now')),
  ('pop5', 'POP Series 5', 17, datetime('now')),
  ('dp1', 'Diamond & Pearl', 130, datetime('now')),
  ('dpp', 'DP Black Star Promos', 56, datetime('now')),
  ('dp2', 'Mysterious Treasures', 124, datetime('now')),
  ('pop6', 'POP Series 6', 17, datetime('now')),
  ('dp3', 'Secret Wonders', 132, datetime('now')),
  ('dp4', 'Great Encounters', 106, datetime('now'));

INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('pop7', 'POP Series 7', 17, datetime('now')),
  ('dp5', 'Majestic Dawn', 100, datetime('now')),
  ('dp6', 'Legends Awakened', 146, datetime('now')),
  ('pop8', 'POP Series 8', 17, datetime('now')),
  ('dp7', 'Stormfront', 106, datetime('now')),
  ('pl1', 'Platinum', 133, datetime('now')),
  ('pop9', 'POP Series 9', 17, datetime('now')),
  ('pl2', 'Rising Rivals', 120, datetime('now')),
  ('pl3', 'Supreme Victors', 153, datetime('now')),
  ('pl4', 'Arceus', 111, datetime('now')),
  ('ru1', 'Pokémon Rumble', 16, datetime('now')),
  ('hgss1', 'HeartGold & SoulSilver', 124, datetime('now')),
  ('hsp', 'HGSS Black Star Promos', 25, datetime('now')),
  ('hgss2', 'HS—Unleashed', 96, datetime('now')),
  ('hgss3', 'HS—Undaunted', 91, datetime('now')),
  ('hgss4', 'HS—Triumphant', 103, datetime('now')),
  ('col1', 'Call of Legends', 106, datetime('now')),
  ('bwp', 'BW Black Star Promos', 101, datetime('now')),
  ('bw1', 'Black & White', 115, datetime('now')),
  ('mcd11', 'McDonald''s Collection 2011', 12, datetime('now')),
  ('bw2', 'Emerging Powers', 98, datetime('now')),
  ('bw3', 'Noble Victories', 102, datetime('now')),
  ('bw4', 'Next Destinies', 103, datetime('now')),
  ('bw5', 'Dark Explorers', 111, datetime('now')),
  ('mcd12', 'McDonald''s Collection 2012', 12, datetime('now'));

INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('bw6', 'Dragons Exalted', 128, datetime('now')),
  ('dv1', 'Dragon Vault', 21, datetime('now')),
  ('bw7', 'Boundaries Crossed', 153, datetime('now')),
  ('bw8', 'Plasma Storm', 138, datetime('now')),
  ('bw9', 'Plasma Freeze', 122, datetime('now')),
  ('bw10', 'Plasma Blast', 105, datetime('now')),
  ('xyp', 'XY Black Star Promos', 216, datetime('now')),
  ('bw11', 'Legendary Treasures', 140, datetime('now')),
  ('xy0', 'Kalos Starter Set', 39, datetime('now')),
  ('xy1', 'XY', 146, datetime('now')),
  ('xy2', 'Flashfire', 110, datetime('now')),
  ('mcd14', 'McDonald''s Collection 2014', 12, datetime('now')),
  ('xy3', 'Furious Fists', 114, datetime('now')),
  ('xy4', 'Phantom Forces', 124, datetime('now')),
  ('xy5', 'Primal Clash', 164, datetime('now')),
  ('dc1', 'Double Crisis', 34, datetime('now')),
  ('xy6', 'Roaring Skies', 112, datetime('now')),
  ('xy7', 'Ancient Origins', 101, datetime('now')),
  ('xy8', 'BREAKthrough', 165, datetime('now')),
  ('mcd15', 'McDonald''s Collection 2015', 12, datetime('now')),
  ('xy9', 'BREAKpoint', 126, datetime('now')),
  ('g1', 'Generations', 117, datetime('now')),
  ('xy10', 'Fates Collide', 129, datetime('now')),
  ('xy11', 'Steam Siege', 116, datetime('now')),
  ('mcd16', 'McDonald''s Collection 2016', 12, datetime('now'));

INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('xy12', 'Evolutions', 113, datetime('now')),
  ('sm1', 'Sun & Moon', 173, datetime('now')),
  ('smp', 'SM Black Star Promos', 251, datetime('now')),
  ('sm2', 'Guardians Rising', 180, datetime('now')),
  ('sm3', 'Burning Shadows', 177, datetime('now')),
  ('sm35', 'Shining Legends', 81, datetime('now')),
  ('sm4', 'Crimson Invasion', 126, datetime('now')),
  ('mcd17', 'McDonald''s Collection 2017', 12, datetime('now')),
  ('sm5', 'Ultra Prism', 178, datetime('now')),
  ('sm6', 'Forbidden Light', 150, datetime('now')),
  ('sm7', 'Celestial Storm', 187, datetime('now')),
  ('sm75', 'Dragon Majesty', 80, datetime('now')),
  ('mcd18', 'McDonald''s Collection 2018', 12, datetime('now')),
  ('sm8', 'Lost Thunder', 240, datetime('now')),
  ('sm9', 'Team Up', 198, datetime('now')),
  ('det1', 'Detective Pikachu', 18, datetime('now')),
  ('sm10', 'Unbroken Bonds', 238, datetime('now')),
  ('sm11', 'Unified Minds', 261, datetime('now')),
  ('sma', 'Hidden Fates Shiny Vault', 94, datetime('now')),
  ('sm115', 'Hidden Fates', 69, datetime('now')),
  ('mcd19', 'McDonald''s Collection 2019', 12, datetime('now')),
  ('sm12', 'Cosmic Eclipse', 272, datetime('now')),
  ('swshp', 'SWSH Black Star Promos', 304, datetime('now')),
  ('swsh1', 'Sword & Shield', 216, datetime('now')),
  ('swsh2', 'Rebel Clash', 209, datetime('now'));

INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('swsh3', 'Darkness Ablaze', 201, datetime('now')),
  ('fut20', 'Pokémon Futsal Collection', 5, datetime('now')),
  ('swsh35', 'Champion''s Path', 80, datetime('now')),
  ('swsh4', 'Vivid Voltage', 203, datetime('now')),
  ('mcd21', 'McDonald''s Collection 2021', 25, datetime('now')),
  ('swsh45sv', 'Shining Fates Shiny Vault', 122, datetime('now')),
  ('swsh45', 'Shining Fates', 73, datetime('now')),
  ('swsh5', 'Battle Styles', 183, datetime('now')),
  ('swsh6', 'Chilling Reign', 233, datetime('now')),
  ('swsh7', 'Evolving Skies', 237, datetime('now')),
  ('cel25c', 'Celebrations: Classic Collection', 25, datetime('now')),
  ('cel25', 'Celebrations', 25, datetime('now')),
  ('swsh8', 'Fusion Strike', 284, datetime('now')),
  ('swsh9tg', 'Brilliant Stars Trainer Gallery', 30, datetime('now')),
  ('swsh9', 'Brilliant Stars', 186, datetime('now')),
  ('swsh10', 'Astral Radiance', 216, datetime('now')),
  ('swsh10tg', 'Astral Radiance Trainer Gallery', 30, datetime('now')),
  ('pgo', 'Pokémon GO', 88, datetime('now')),
  ('mcd22', 'McDonald''s Collection 2022', 15, datetime('now')),
  ('swsh11', 'Lost Origin', 217, datetime('now')),
  ('swsh11tg', 'Lost Origin Trainer Gallery', 30, datetime('now')),
  ('swsh12', 'Silver Tempest', 215, datetime('now')),
  ('swsh12tg', 'Silver Tempest Trainer Gallery', 30, datetime('now')),
  ('svp', 'Scarlet & Violet Black Star Promos', 200, datetime('now')),
  ('swsh12pt5', 'Crown Zenith', 160, datetime('now'));

INSERT OR IGNORE INTO pokemon_catalog_sets (set_id, set_name, total_cards, seeded_at) VALUES
  ('swsh12pt5gg', 'Crown Zenith Galarian Gallery', 70, datetime('now')),
  ('sv1', 'Scarlet & Violet', 258, datetime('now')),
  ('sve', 'Scarlet & Violet Energies', 16, datetime('now')),
  ('sv2', 'Paldea Evolved', 279, datetime('now')),
  ('sv3', 'Obsidian Flames', 230, datetime('now')),
  ('sv3pt5', '151', 207, datetime('now')),
  ('sv4', 'Paradox Rift', 266, datetime('now')),
  ('sv4pt5', 'Paldean Fates', 245, datetime('now')),
  ('sv5', 'Temporal Forces', 218, datetime('now')),
  ('sv6', 'Twilight Masquerade', 226, datetime('now')),
  ('sv6pt5', 'Shrouded Fable', 99, datetime('now')),
  ('sv7', 'Stellar Crown', 175, datetime('now')),
  ('sv8', 'Surging Sparks', 252, datetime('now')),
  ('sv8pt5', 'Prismatic Evolutions', 180, datetime('now')),
  ('sv9', 'Journey Together', 190, datetime('now')),
  ('sv10', 'Destined Rivals', 244, datetime('now')),
  ('zsv10pt5', 'Black Bolt', 172, datetime('now')),
  ('rsv10pt5', 'White Flare', 173, datetime('now')),
  ('me1', 'Mega Evolution', 188, datetime('now')),
  ('me2', 'Phantasmal Flames', 130, datetime('now')),
  ('me2pt5', 'Ascended Heroes', 250, datetime('now')),
  ('me3', 'Perfect Order', 124, datetime('now'));

